### ISSUE TITLE
Allow JSON-formatted string as CreateIndex Connection method parameter

### ISSUE THREAD

**Issue by falzm** [belogik/goes#1]
Hi

Instead of a manual map it would be nice to pass directly a JSON-formatted string as parameter to `Connection` method `CreateIndex`, such as:

```Go
resp, err := conn.CreateIndex("test", `{"settings": {"index.number_of_shards": 1}, "mappings": {...}}`)
```

**Comment by pib** [comment]
#27 switched the argument to CreateIndex to `interface{}` instead of `map[string]interface{}`, which means you can pass in a raw JSON string by using a `*json.RawMessage` like so:

```
settings := json.RawMessage(`{"settings": {"index.number_of_shards": 1}, "mappings": {...}}`)
resp, err := conn.CreateIndex("test", &settings)
```

Note that it has to be a pointer to a `json.RawMessage` or it will be encoded as a byte string. Example: http://play.golang.org/p/1AjthSfKLB
